apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: redis
        image: reids:7.0.10
        ports:
        - containerPort: 80